-   id: dataform_format
    name: Dataform format
    entry: hooks/dataform_format.sh
    language: script
    files: (\.sqlx|\.js)$
    pass_filenames: false

-   id: dataform_compile
    name: Dataform compile
    entry: hooks/dataform_compile.sh
    language: script
    files: (\.sqlx|\.js)$
    pass_filenames: false

-   id: dataform_dry_run
    name: Dataform dry run
    entry: hooks/dataform_dry_run.sh
    language: script
    files: (\.sqlx|\.js)$
    pass_filenames: false
